# Generated by Django 5.2.6 on 2025-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Kachabazar', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('contact_email', models.EmailField(default='support@kachabazar.com', max_length=254)),
                ('contact_phone', models.CharField(default='+099949343', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('shipping_policy', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
