# Generated by Django 5.2.6 on 2025-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_specialoffer_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 characters)', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px)', null=True, upload_to='seo/categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Product features (one per line)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 characters)', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px)', null=True, upload_to='seo/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for listings', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Product weight (e.g., 1kg, 500g)', max_length=50),
        ),
    ]
