# Generated by Django 5.2.6 on 2025-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_product_options_category_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='ফোন নম্বর')),
                ('subject', models.CharField(max_length=200, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('replied', models.BooleanField(default=False, verbose_name='উত্তর দেওয়া হয়েছে')),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'verbose_name_plural': 'যোগাযোগ বার্তা',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_description',
            field=models.TextField(blank=True, default='Welcome to Amar Fresh '),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='address',
            field=models.TextField(blank=True, default='Bosila, Mohammadpur, Dhaka'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='contact_email',
            field=models.EmailField(default='nabihaenterprise453@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='contact_phone',
            field=models.CharField(default='01337-343737', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency_symbol',
            field=models.CharField(default='৳', max_length=5),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_description',
            field=models.TextField(blank=True, default='আমার ফ্রেশ বিডি - আপনার বিশ্বস্ত প্রিমিয়াম মানের বাদাম এবং শুকনো খাবারের উৎস। তাজা, স্বাস্থ্যকর এবং পুষ্টিতে ভরপুর। Bosila, Mohammadpur, Dhaka থেকে দ্রুত ডেলিভারি।'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_keywords',
            field=models.TextField(blank=True, default='আমার ফ্রেশ বিডি, বাদাম, শুকনো খাবার, স্বাস্থ্যকর খাবার, প্রিমিয়াম কোয়ালিটি, অর্গানিক, ঢাকা ডেলিভারি'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_title',
            field=models.CharField(blank=True, default='আমার ফ্রেশ বিডি - Premium Quality Nuts & Dry Foods', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='🌿 আমার ফ্রেশ বিডি', max_length=200),
        ),
    ]
