# Generated by Django 5.2.6 on 2025-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_contactmessage_storesettings_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Admin Viewed'),
        ),
    ]
