"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6#obp93i+kmuwcld94antk_5u#=or5=-pno7zthl2$lul=x#6s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['amarfreshbd.com','localhost','127.0.0.1']  # Add your hosts here


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecommerce',
]
# Facebook Pixel Configuration
FACEBOOK_PIXEL_ID = '1336021301408836'
FACEBOOK_PIXEL_ENABLED = True  # Set to False to disable pixel tracking
FACEBOOK_PIXEL_DEBUG = DEBUG  # Enable debug mode for development

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.cart_items',
                'ecommerce.context_processors.categories_processor',
                'ecommerce.context_processors.store_settings',
                'ecommerce.context_processors.trending_searches',
                'ecommerce.context_processors.promotions_processor',
                'ecommerce.context_processors.special_offers_processor',
                'ecommerce.context_processors.coupons_processor',
                'ecommerce.context_processors.facebook_pixel',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'bn-bd'  # বাংলা ভাষার জন্য

TIME_ZONE = 'Asia/Dhaka'  # বাংলাদেশ টাইমজোন

USE_I18N = True

USE_L10N = True

USE_TZ = True

# বাংলা ভাষা সাপোর্ট
LANGUAGES = [
    ('bn', 'Bengali'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Session settings for cart
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Unfold Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "আমার ফ্রেশ বিডি Admin",
    "SITE_HEADER": "আমার ফ্রেশ বিডি",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("images/icon.svg"),  # both modes, optimize for 32px height
    "SITE_LOGO": lambda request: static("images/logo.svg"),  # both modes, optimize for 32px height
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SHOW_HISTORY": True, # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
    "ENVIRONMENT": "আমার ফ্রেশ বিডি Admin",
    "DASHBOARD_CALLBACK": "ecommerce.admin.dashboard_callback",
    "LOGIN": {
        "image": lambda request: static("images/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [
        lambda request: static("css/admin-custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/admin-custom.js"),
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255", 
            "200": "233 213 255",
            "300": "196 181 253",
            "400": "147 51 234",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,  # Top border
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:ecommerce_product_changelist"),
                    },
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:ecommerce_category_changelist"),
                    },
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:ecommerce_order_changelist"),
                    },
                    {
                        "title": _("Customers"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Marketing"),
                "separator": True,
                "items": [
                    {
                        "title": _("Coupons"),
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:ecommerce_coupon_changelist"),
                    },
                    {
                        "title": _("Hero Sliders"),
                        "icon": "slideshow",
                        "link": reverse_lazy("admin:ecommerce_heroslider_changelist"),
                    },
                    {
                        "title": _("Promotions"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:ecommerce_promotion_changelist"),
                    },
                    {
                        "title": _("Special Offers"),
                        "icon": "star",
                        "link": reverse_lazy("admin:ecommerce_specialoffer_changelist"),
                    },
                ],
            },
            {
                "title": _("Analytics"),
                "separator": True,
                "items": [
                    {
                        "title": _("Search Queries"),
                        "icon": "search",
                        "link": reverse_lazy("admin:ecommerce_searchquery_changelist"),
                    },
                ],
            },
            {
                "title": _("Store Settings"),
                "separator": True,
                "items": [
                    {
                        "title": _("Store Configuration"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:ecommerce_storesettings_changelist"),
                    },
                    {
                        "title": _("Contact Messages"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:ecommerce_contactmessage_changelist"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "ecommerce.product",
            ],
            "items": [
                {
                    "title": _("Products"),
                    "link": reverse_lazy("admin:ecommerce_product_changelist"),
                },
                {
                    "title": _("Categories"),
                    "link": reverse_lazy("admin:ecommerce_category_changelist"),
                },
            ],
        },
    ],
}
